### ISSUE TITLE
Issue in donloading https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.6/kotlin-compiler-embeddable-1.0.6.jar

### ISSUE THREAD

**Issue by thatsankur** [igalata/Bubble-Picker#1]
Gradle is struck at downloading https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.6/kotlin-compiler-embeddable-1.0.6.jar

This is really nice demo but I can not see it working because of above issue please let me know how I can resolve it 

thought downloading above file works like a charm but gradle was able to download 7mb in 5 hrs :/

**Comment by igalata** [comment]
Hello @thatsankur 
Can you please provide me with more details? Is your project in Java or Kotlin? Could you please share your build.gradle file?

**Comment by thatsankur** [comment]
@igalata 
I am just trying the sample app without any changes and I don't think there is any issue with application but the download of kotlin during build process via gradle is taking huge amount of time  (my internet connection is fine) 

it is very very slow :/

AnkurNp1:Bubble-Picker-develop ankur.singh2$ ./gradlew installOriginalDebug
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.5/kotlin-compiler-embeddable-1.0.5.jar
> Configuring > 0/3 projects > root project > **249 KB/21.96 MB downloadedc**

Do you face similar issue ? and what can be the possible work around this issue ?

**Comment by thatsankur** [comment]
@igalata 

It worked when I changed  
ext.kotlin_version = '1.1.0' form 1.0.6

earlier it was dead slow :-D 

Thanks :)

**Comment by igalata** [comment]
@thatsankur It's great ;)
