### ISSUE TITLE
Change bubble speed

### ISSUE THREAD

**Issue by uhlukguy** [igalata/Bubble-Picker#10]
Hi thanks for creating this library,
I wanted to know if it's possible to change the speed of the bubbles showing up the screen. The default speed is a bit too slow for me. Thanks.

**Comment by igalata** [comment]
Hello @uhlukguy 
There is no such functionality now, but I'll implement it very soon. Thanks for the idea! :)

**Comment by lanrehnics** [comment]
Awesome library but really need to be able to speed it up.. kinda too slow..

**Comment by ismailtosun** [comment]
so slow

**Comment by shriharsha-bhagwat** [comment]
I have one requirement where in i need the items to be placed in the sort order. Is it possible?

**Comment by zhaonian** [comment]
Any update on this?

**Comment by D4rracuda** [comment]
Please make it available faster. Really need this
