### ISSUE TITLE
Can not show bubble picker after finishing a background task.

### ISSUE THREAD

**Issue by think-twice-code-once** [igalata/Bubble-Picker#14]
Hi Irina, 
Thank you so much for your efforts to build this library.
Basically, it works fine if I init and show it in one main thread:

 ```
@AfterViews
    void init() {
        bubblePicker.setItems(new ArrayList<PickerItem>());
        bubblePicker.setBubbleSize(10);

        addItems();
    }
```

```
 @UiThread
    void addItems() {
        String[] testDatas = new String[]{"Item 1", "Item 21", "Item 3", "Item 4", "Item 5"};
        for (String data : testDatas) {
            PickerItem pickerItem = new PickerItem(data, null, false, ContextCompat.getColor(MainActivity.this, R.color.colorAccent),
                    null, 0f, Typeface.create("", Typeface.BOLD), null, 20f, ContextCompat.getDrawable(MainActivity.this, R.drawable.abc), true);
            if (bubblePicker.getItems() != null) {
                bubblePicker.getItems().add(pickerItem);
            }
        }

        bubblePicker.setListener(new BubblePickerListener() {
            @Override
            public void onBubbleSelected(@NotNull PickerItem pickerItem) {
                Toast.makeText(MainActivity.this, pickerItem.getTitle(), Toast.LENGTH_SHORT).show();
            }


            @Override
            public void onBubbleDeselected(@NotNull PickerItem pickerItem) {

            }
        });
    }
```

**But it's not working at all if I implement it like that:**

```
@AfterViews
    void init() {
        bubblePicker.setItems(new ArrayList<PickerItem>());
        bubblePicker.setBubbleSize(10);

        doSomething();
    }
```
```

 @Background
    void doSomething() {
        // get data from server or something like that...
        SystemClock.sleep(1000);
        addItems();
    }
```
I'm sure that it called addItems() method when the main thread is cameback.
Please help.

**Comment by igalata** [comment]
Hi @think-twice-code-once :)

The first option is to do all the needed work before the screen actually opens. But it's not always acceptable. Try to call `onPause()` and `onResume()` methods of the `BubblePicker` one after another when you're done (`onPause()` is not needed if you've not called `onResume()` before it). If it doesn't work I'll research it more carefully to help you to resolve this issue

**Comment by think-twice-code-once** [comment]
oh my god it working now ! 
I spent a whole day to figure out why but got nothing, even I asked help from my leader :).
How could I didn't try this solution :(. 
Thank you so much.
By the way :
"onPause() is not needed if you've not called onResume() before it"
you mean: 
"onPause() is not needed if you've not called onResume() **after** it"
right ?

**Comment by igalata** [comment]
Oh, it's great! :1st_place_medal: I'm happy I could help you :)
No, not exactly. If you do some job in the background, you probably will have two `onResume()` method calls (when your activity actually resumes and when your background job is done), right? So you should make sure, that when you call `onResume()` anywhere your job is done and the view wasn't resumed just before. Otherwise you should call `onPause()` before calling `onResume()`.  I'm not really sure If I've explained properly, so I'll gladly answer all your questions :)

**Comment by think-twice-code-once** [comment]
Okay I got it, thank you.
Just another thing, is there any way to show all items in center of screen immediately ?

**Comment by igalata** [comment]
Not right now, but I can easily implement it tonight. I'll notify you when I update the library ;)

**Comment by think-twice-code-once** [comment]
Glad to hear that, I'm looking forward to hearing from you. Thank you in advance 👍 .

**Comment by igalata** [comment]
@think-twice-code-once 
Check out a new version :) 
You can use `centerImmediately` variable of the `BubblePicker` to achieve the effect

**Comment by think-twice-code-once** [comment]
@igalata thank you very much, it really helped me a lot. 
It works fine now. thanks again :).

**Comment by igalata** [comment]
@think-twice-code-once I'm glad I could help you :)

**Comment by Yazdani1** [comment]
hello..i want to pass intent for going next activity.here anyone can tell me how can i pass intent ,when i select bubble option i want to add intent.is it possible.thanks

**Comment by atiqulalam** [comment]
@igalata @think-twice-code-once 

please help me, i want to show bubble after getting API response in background, how to do that ?
@think-twice-code-once 
please share your code

**Comment by maheswarich** [comment]
Hi how to change bubble size at run time any help its appreciate

**Comment by RapoluSaikrishnaRao** [comment]
Hi i have below two issues.
1) Please tell me,How to change Bubble Picker Size.
2) one more thing is that after getting response from API am showing data on Bubble Pickers(Bubble Picker functionality implemented in my Fragment Class). but main problem here is  that when am clicking particulate bubble am navigating another screen(another Fragment) and coming back main screen(Fragment Class) and doing like this two or three time(Going inside coming back side) am getting the below error.then app going to be crashed.

 java.lang.NullPointerException: Attempt to invoke virtual method 'org.jbox2d.collision.shapes.Shape org.jbox2d.dynamics.Fixture.getShape()' on a null object reference                                                                               at com.igalata.bubblepicker.physics.CircleBody.reset(CircleBody.kt:91)                                                                               at com.igalata.bubblepicker.physics.CircleBody.increase(CircleBody.kt:82)                                                                               at com.igalata.bubblepicker.physics.CircleBody.resize(CircleBody.kt:66)                                                                               at com.igalata.bubblepicker.physics.Engine.move(Engine.kt:55)                                                                               at com.igalata.bubblepicker.rendering.PickerRenderer.onDrawFrame(PickerRenderer.kt:67)                                                                               at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1553)                                                                               at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253) 

Please tell me why am getting these error and resolve my problem ASAP am waiting for your replay.
