### ISSUE TITLE
Getting java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jbox2d.dynamics.contacts.Contact.init(org.jbox2d.dynamics.Fixture, org.jbox2d.dynamics.Fixture)' on a null object reference

### ISSUE THREAD

**Issue by meethdjain** [igalata/Bubble-Picker#18]
Hi,

I'm trying to use the library in my app & I'm getting the following error. Could you review the code & let me know if I'm missing out anything in the code.

Thanks

Lib Version : v 0.2.1
Device : Nexus 6P

Sample Code : 

public class MainActivity extends AppCompatActivity {

  BubblePicker mBubblePicker;

  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    mBubblePicker = (BubblePicker) findViewById(R.id.picker);
    ArrayList<PickerItem> pickerItems = new ArrayList<>();
    for (int i = 0; i < 5; i++) {
      pickerItems.add(new PickerItem("Hello" + i));
    }
    mBubblePicker.setItems(pickerItems);
  }

  @Override protected void onResume() {
    super.onResume();
    mBubblePicker.onResume();
  }

  @Override protected void onPause() {
    super.onPause();
    mBubblePicker.onPause();
  }
}

**Comment by igalata** [comment]
Hello @meethdjain 
It seems like something went wrong in `World` class. Could you please share the whole stacktrace and some steps to reproduce the bug if possible. Thanks!

**Comment by meethdjain** [comment]
Sure @igalata 

Crash happens on launching the activity.

Stacktrace : 

04-27 13:19:30.865 12781-12833/com.example.bubblepicker 
E/AndroidRuntime: FATAL EXCEPTION: GLThread 189
                                                                                                     Process: com.example.bubblepicker , PID: 12781
                                                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jbox2d.dynamics.contacts.Contact.init(org.jbox2d.dynamics.Fixture, org.jbox2d.dynamics.Fixture)' on a null object reference
                                                                                                         at org.jbox2d.dynamics.World.popContact(World.java:198)
                                                                                                         at org.jbox2d.dynamics.ContactManager.addPair(ContactManager.java:108)
                                                                                                         at org.jbox2d.collision.broadphase.BroadPhase.updatePairs(BroadPhase.java:187)
                                                                                                         at org.jbox2d.dynamics.ContactManager.findNewContacts(ContactManager.java:152)
                                                                                                         at org.jbox2d.dynamics.World.step(World.java:540)
                                                                                                         at com.igalata.bubblepicker.physics.Engine.move(Engine.kt:121)
                                                                                                         at com.igalata.bubblepicker.rendering.PickerRenderer.onDrawFrame(PickerRenderer.kt:67)
                                                                                                         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
                                                                                                         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by igalata** [comment]
@meethdjain What version of the library do you use? It seems like it's not the latest one

**Comment by meethdjain** [comment]
I'm using v0.2.1.

Looks like there's an issue with using the library in my existing project.
Tried out the library in a new project, works fine :)

**Comment by igalata** [comment]
Oh it's great, I was going to create an issue in jbox2d repo :)

**Comment by anas-ambri** [comment]
@meethdjain Running into the same issue. Did you manage to figure out what the problem was?
I have a feeling it has something to do with my proguard configuration.

**Comment by omhack** [comment]
I'm facing this issue, any news?
Thanks

**Comment by LorenzoDeM** [comment]
Just add, in your proguard file:
-keep class com.igalata.bubblepicker{ * ;}
-keep class org.jbox2d.**{ * ;}

**Comment by pingfangx** [comment]
I got the same issue.
## The solution
Add the rule to your proguard rules file.

    -keepclassmembers class * extends org.jbox2d.dynamics.contacts.Contact{
        public <init>(...);
    }

It will keep constructors of any class wich extends org.jbox2d.dynamics.contacts.Contact.

## The reason
When use ProGuard
> The shrinking step detects and removes unused classes, fields, methods and attributes.

It will remove the constructor of org.jbox2d.dynamics.contacts.CircleContact.  
You can see it in usage.txt like

    org.jbox2d.dynamics.contacts.CircleContact:
        41:42:public CircleContact(org.jbox2d.pooling.IWorldPool)

## More details
The exception is thrown from 

    org.jbox2d.dynamics.World#popContact

    public Contact popContact(Fixture fixtureA, Fixture fixtureB) {
        ShapeType type1 = fixtureA.getType();
        ShapeType type2 = fixtureB.getType();
        ContactRegister reg = this.contactStacks[type1.intValue][type2.intValue];
        IDynamicStack<Contact> creator = reg.creator;
        if (creator != null) {
            Contact c;
            if (reg.primary) {
                c = (Contact)creator.pop();
                c.init(fixtureA, fixtureB);
                return c;
            } else {
                c = (Contact)creator.pop();
                c.init(fixtureB, fixtureA);
                return c;
            }
        } else {
            return null;
        }
    }
    
    The c is null, the assignment of contactStacks:
    
    org.jbox2d.dynamics.World#World(org.jbox2d.common.Vec2, boolean, org.jbox2d.pooling.IWorldPool)
    org.jbox2d.dynamics.World#initializeRegisters
        this.addType(this.pool.getCircleContactStack(), ShapeType.CIRCLE, ShapeType.CIRCLE);
    org.jbox2d.dynamics.World#addType
        this.contactStacks[type1.intValue][type2.intValue] = register;
    
    
    org.jbox2d.pooling.normal.DefaultWorldPool#getCircleContactStack
    public final IDynamicStack<Contact> getCircleContactStack() {
        return this.ccstack;
    }
    
    org.jbox2d.pooling.normal.DefaultWorldPool#DefaultWorldPool
        this.ccstack = new MutableStack(CircleContact.class, 10, this.classes, this.args);
        
    org.jbox2d.pooling.normal.MutableStack#MutableStack(java.lang.Class<T>, int, java.lang.Class<?>[], java.lang.Object[])
    org.jbox2d.pooling.normal.MutableStack#extendStack
    
    private void extendStack(int argSize) {
        T[] newStack = (Object[])((Object[])Array.newInstance(this.sClass, argSize));
        if (this.stack != null) {
            System.arraycopy(this.stack, 0, newStack, 0, this.size);
        }

        for(int i = 0; i < newStack.length; ++i) {
            try {
                if (this.params != null) {
                    newStack[i] = this.sClass.getConstructor(this.params).newInstance(this.args);
                } else {
                    newStack[i] = this.sClass.newInstance();
                }
            } catch (InstantiationException var5) {
                log.error("Error creating pooled object " + this.sClass.getSimpleName(), var5);

                assert false : "Error creating pooled object " + this.sClass.getCanonicalName();
            } catch (IllegalAccessException var6) {
                log.error("Error creating pooled object " + this.sClass.getSimpleName(), var6);

                assert false : "Error creating pooled object " + this.sClass.getCanonicalName();
            } catch (IllegalArgumentException var7) {
                log.error("Error creating pooled object " + this.sClass.getSimpleName(), var7);

                assert false : "Error creating pooled object " + this.sClass.getCanonicalName();
            } catch (SecurityException var8) {
                log.error("Error creating pooled object " + this.sClass.getSimpleName(), var8);

                assert false : "Error creating pooled object " + this.sClass.getCanonicalName();
            } catch (InvocationTargetException var9) {
                log.error("Error creating pooled object " + this.sClass.getSimpleName(), var9);

                assert false : "Error creating pooled object " + this.sClass.getCanonicalName();
            } catch (NoSuchMethodException var10) {
                log.error("Error creating pooled object " + this.sClass.getSimpleName(), var10);

                assert false : "Error creating pooled object " + this.sClass.getCanonicalName();
            }
        }

        this.stack = newStack;
        this.size = newStack.length;
    }
    
    In method extendStack,because constructor has removed by ProGuard, getConstructor will throw NoSuchMethodException.  
    Finally in method popContact,c will be null.
