### ISSUE TITLE
Make the view refresh its items

### ISSUE THREAD

**Issue by FlorentAnders** [igalata/Bubble-Picker#19]
In my app, adding items seems to be too late for the BubblePicker to show them up before recreating, how can I force BubblePicker to refresh without restarting my activity?

Greetings!

**Comment by igalata** [comment]
Hello @FlorentAnders :)
Try to call `picker.onPause()` and `picker.onResume()` methods one after another when your data is ready. It should work out

**Comment by FlorentAnders** [comment]
I had already tried that but it hasn't worked again now. The new items appear when the device orientation changes. recreate() didn't work either.

**Comment by FlorentAnders** [comment]
My current solution is to fully recreate the application after 2,5 seconds. I think this will do for the moment!

**Comment by DrewGregory** [comment]
To those who may find this interesting...
it seems to me that you can reinitialize the rendering by resetting its visibility. Just try `picker.setVisibility(View.GONE);` followed by `picker.setVisibility(View.VISIBLE);`
