### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by truth-seeker0** [igalata/Bubble-Picker#24]
I'm trying to run an example.
Example from your description does not work.
I changed the example to:
picker.setItems(new ArrayList<PickerItem>() {{
            for (int i = 0; i < titles.length; ++i) {
                add(new PickerItem(titles[i],
                        ContextCompat.getDrawable(MainActivity.this, images.getResourceId(i, 0)),
                        true,
                        colors.getColor((i * 2) % 8, 0),
                        null,
                        ContextCompat.getColor(MainActivity.this, android.R.color.white)
                        ));
            }
        }});

I get this exception:
 java.lang.OutOfMemoryError: Failed to allocate a 30862956 byte allocation with 16777168 free bytes and 17MB until OOM
On the emulator and on the real device.

**Comment by igalata** [comment]
Hi @truth-seeker0 
Your images size could a reason of this issue. Aren't they too large?

**Comment by truth-seeker0** [comment]
For example, I use your pictures - countries.
Is there a need to reduce them?

**Comment by piffarettig** [comment]
Same issue happeing here. Probably because images are huge. Tried something like:

```
 public int getTotalCount() {
      return 3;
}
```
And it worked. So it works with fewer images. Probably the workaround for this is to compress the images
