### ISSUE TITLE
The library isn't working!

### ISSUE THREAD

**Issue by ScienciaWilson** [igalata/Bubble-Picker#27]
I really appreciate the effort that you have put into this library and how extravagantly beautiful it is but..

Whenever I try to use the library, it keeps on giving me the error message after the add statement...

PickerItem() in PickerItem cannot be applied to:
Expected Parameters:
Actual Arguments:

I am coding in Java and this is my source code...

`    final String[] titles = getResources().getStringArray(R.array.names);
    final TypedArray colors = getResources().obtainTypedArray(R.array.colors);
    final TypedArray images = getResources().obtainTypedArray(R.array.images);
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        bubblePicker.setItems(new ArrayList<PickerItem>() {{
            for (int i = 0; i < titles.length; ++i) {
                add(new PickerItem(titles[i], colors.getColor((i * 2) % 8, 0),
                        ContextCompat.getColor(MainActivity.this, android.R.color.white),
                        ContextCompat.getDrawable(MainActivity.this, images.getResourceId(i, 0)))
            }
        }});`

The project I'm working on is extremely urgent so I am begging you to please help me out.

**Comment by igalata** [comment]
Provide me with more details please

**Comment by ScienciaWilson** [comment]
I have updated the info

**Comment by igalata** [comment]
I'm checking your code right now. It seems to be ok except for the missing `);` symbols at the end of the `add()` function call. Could you check it?

**Comment by lingarajsankaravelu** [comment]
@ScienciaWilson . I have tried the library with java as well. Here is the repo , where you can refer your code with [https://github.com/lingarajsankaravelu/MyApplication](url)

**Comment by ScienciaWilson** [comment]
Thankyou! It is working now.
