### ISSUE TITLE
Weird bug on Nexus 7

### ISSUE THREAD

**Issue by FlorentAnders** [igalata/Bubble-Picker#30]
Not a OS issue, happens on 7.1 as on 4.4 on Nexus 7...

https://drive.google.com/open?id=0B7PIyoRznmeualRwSHJIcmJMZVE

Any idea where this might come from? Not happening on phones.

**Comment by igalata** [comment]
Could you please share your activity/fragment code? Where do you pass the data to the picker? Seems like something went wrong with textures, but it's weird that only Nexus 7 devices are affected

**Comment by FlorentAnders** [comment]
Maybe tablets at all are affected...

final TypedArray colors = getResources().obtainTypedArray(R.array.colors);
        imageView.setImageBitmap(bitmap);
        final Drawable topStoriesImage = imageView.getDrawable();

        picker.getItems().add(index, new PickerItem(name,
                null, true, getResources().getColor(R.color.light_accent_color), new BubbleGradient(colors.getColor((index * 2) % 8, 0), colors.getColor((index * 2) % 8 + 1, 0),
                BubbleGradient.VERTICAL), 0.5f,
                Typeface.DEFAULT, getResources().getColor(R.color.white), 40f, topStoriesImage, false));

I am loading the images via Picasso from the ImageView. The color array is exactly the one you have in the sample.

**Comment by igalata** [comment]
I'll try to reproduce this issue on a emulator to fix it. Could you also please share the code where you're downloading the image?

**Comment by FlorentAnders** [comment]
loadTarget(TopStoriesLayout, 0, getResources().getString(R.string.google_news_top_stories), "http://i.imgur.com/EZE7Lce.jpg");

       private void loadTarget(final ImageView imageView, final int index, final String title, String url){
        Target target = new Target() {
            @Override
            public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                bitmapLoaded(imageView, bitmap, index, title);
            }

            @Override
            public void onBitmapFailed(Drawable errorDrawable) {
                bitmapCouldNotLoad(index, title);
            }

            @Override
            public void onPrepareLoad(Drawable placeHolderDrawable) {}
        };

        Picasso.with(this).load(url).into(target);
    }

**Comment by igalata** [comment]
Ok, thanks. I'll check it now

**Comment by igalata** [comment]
@FlorentAnders 
I have some thoughts about this issue. Can it be connected with the image size? If it's not downloaded yet, the texture will not be ready. Could you check the animation with smaller image?
Also do you call `picker.onPause()` and `picker.onResume()` after the image is ready? It's also important. 
Also I think it's better to pass the items to the picker after the image is downloaded.

**Comment by FlorentAnders** [comment]
I'm caching the images before even opening the activity that requires these. As it is working on every device except this Nexus, I can't really imagine that is the cause... Calling onPause and onResume after the images are loaded could be something I could try, good idea.

**Comment by FlorentAnders** [comment]
That didn't help. Changing the orientation neither, reloading the activity a second time where the icons should be loaded didn't help either.

**Comment by igalata** [comment]
Seems like I've found something. Please, take a look at [this answer](http://stackoverflow.com/a/16093658) on stackoverflow. Some devices (like Nexus 7) doesn't support non-power of two textures. The size of your texture is 800x494, while it should be e.g. 1024x512 (2^10x2^9). If it works it'll be the most weird issue I've ever seen :D

**Comment by FlorentAnders** [comment]
What should I do exactly? Haven't really understood it from the answer, sorry:D

**Comment by igalata** [comment]
Sorry, it's not about the image size, it's about the texture size. So the changes should be done on my side. For now the texture size is hardcoded to 300, I need to change it to the power of 2 (256 or 512). And it can be the solution

**Comment by igalata** [comment]
@FlorentAnders try the v0.2.3 version out

**Comment by FlorentAnders** [comment]
Okay, downloading it now.

**Comment by FlorentAnders** [comment]
May I know the changelogs of 0.2.2 and 0.2.3?:)

**Comment by FlorentAnders** [comment]
Yes, working now, lol.
