### ISSUE TITLE
About method setItems

### ISSUE THREAD

**Issue by AKILLIMUSTAFA** [igalata/Bubble-Picker#31]
Did the parameters change? I'm getting an error.

![issue](https://cloud.githubusercontent.com/assets/11073644/26280752/cefc18b2-3de8-11e7-8684-c75c9d12abe1.png)

**Comment by igalata** [comment]
Hi, @AKILLIMUSTAFA 
The amount of the parameters has increased. Try to pass `null` and `false` for the `icon` and `iconOnTop` parameters respectively. In the next version it will be possible to setup the picker using adapter, so it'd much easier
