### ISSUE TITLE
Java example not working

### ISSUE THREAD

**Issue by davidsaraiva** [igalata/Bubble-Picker#32]
Hi, I came across with your work the last weekend, and I'm testing it on a new application I'm developing, when I tried your java code to create the picker Items it was not compiling because the constructor you were using does not exists...I was able to change it using the constructor PickerItem(Title, Drawable, iconOnTop, Color) but I came across with another problem, the title does not appear, I only see the bubbles with the drawable already displayed, and when I click the bubble enlarges, apply an alpha effect with the same drawable.
Can you help me telling how I can present the bubbles the same way you did in your example app? Thank you

**Comment by igalata** [comment]
Hi @davidsaraiv 
Seems like it's a bug, I'll check it right now. Thanks!

**Comment by igalata** [comment]
try this snippet out 

```
bubblePicker.setItems(new ArrayList<PickerItem>() {{
            for (int i = 0; i < 20; ++i)
                add(new PickerItem("testTitle" + i, null,
                        true, ContextCompat.getColor(Test.this, R.color.purpleStart), null, 0.5f, Typeface.DEFAULT,
                        ContextCompat.getColor(Test.this, android.R.color.white), 30,
                        ContextCompat.getDrawable(Test.this, R.drawable.brazil)));
        }});

```

In Java it's more complicated to use this constructor without named arguments. I plan to update the library to make it possible to setup the picker using adapter tonight. It's much more convenient.

**Comment by davidsaraiva** [comment]
Thank you, gonna try later ill update my results

**Comment by igalata** [comment]
@davidsaraiv try the new version (v0.2.4) out. You can now setup the picker using an adapter. Also the properties of the `PickerItem` have setters now. For the usage example take a look at the updated readme

**Comment by shriharsha-bhagwat** [comment]
I have one requirement where in i need the items to be placed in the sort order. Is it possible?
