### ISSUE TITLE
Text and Bubble size?

### ISSUE THREAD

**Issue by myinnos** [igalata/Bubble-Picker#4]
This lib is very interesting 👍  I want to know how to increase the bubble size and text size on bubble ?

**Comment by igalata** [comment]
Hello, @myinnos 
Thanks :) You can change the bubbles size by setting the `picker.bubbleSize` variable the appropriate size (`BubbleSize.SMALL`, `BubbleSize.MEDIUM` or `BubbleSize.LARGE`) in Kotlin or using the `picker.setBubbleSize()` method in Java. And the text will be resized according this selected size. A bit later it'll be possible to more flexible customize the animation

**Comment by myinnos** [comment]
Thanks mate 👍
