### ISSUE TITLE
Add an extra icon to the bubble Picker?

### ISSUE THREAD

**Issue by anitaa1990** [igalata/Bubble-Picker#8]
Hi I would like to add the drawable as an icon above the text rather than as a background. Please find attached screenshot:

![example](https://cloud.githubusercontent.com/assets/22608780/24501937/440a9d5c-1569-11e7-9133-7958623d8eee.png)

Please let me know if this is possible. 

Thanks for your help!

**Comment by igalata** [comment]
Hello @anitaa1990
There is no such feature at the moment, but I can easily implement it very soon. I'll notify you when it's ready

**Comment by anitaa1990** [comment]
Thanks a lot 👍  Appreciate it!

**Comment by igalata** [comment]
@anitaa1990 It's possible to add extra icon in the current (v0.2) version. Please, review changelog on readme for more details :)

**Comment by anitaa1990** [comment]
Hi @igalata Thanks a lot for the quick response! It is working very good :) 

Just a small doubt: when ever I click on a bubble the background color becomes transparent. And when I checked out the library, there is an option to pass an image as a background. But I would like to only change the color of the bubble background (and don't have to add an image to it). Is there a way to do this?

**Comment by igalata** [comment]
@anitaa1990 Thanks for your attention to the animation :) 
Check the `overlayAlpha` variable. If it's 1, the background won't be transparent. Or you want to change the background color when the bubble is selected?

**Comment by anitaa1990** [comment]
No the overlayAlpha is perfect 👍  Thanks a lot :)

**Comment by igalata** [comment]
Great! ;)

**Comment by anitaa1990** [comment]
@igalata Hey sorry to keep bugging you with questions :) 

Just one more: I checked out the demo app you have and the animation there is loaded really quickly. But in my app, it takes a while for the animation to load. Is there something I need to add to make the bubbles load faster?

**Comment by igalata** [comment]
It's ok :) 
Can you share your code? I'll check it to advise you

**Comment by anitaa1990** [comment]
![example](https://cloud.githubusercontent.com/assets/22608780/24541185/006fb518-1614-11e7-9013-b03f09974600.png)

Thanks :)

**Comment by igalata** [comment]
Your code seems to be ok, I'll check it one more time today. But I think the images could be the reason of the problem. Are they too large? Or the problem occurs even if you don't pass the images at all?

**Comment by anitaa1990** [comment]
Good point! I just checked the image sizes and all are 18KB. But I tried it without the images and same result.

**Comment by igalata** [comment]
It's really strange issue. I'll let know when I fix it

**Comment by igalata** [comment]
@anitaa1990 Hello :)
I didn't find a solution yet, but could you share a video how the animation works in your case?
