### ISSUE TITLE
java.lang.AssertionError in Fragment

### ISSUE THREAD

**Issue by KentBryan** [igalata/Bubble-Picker#89]
![Bubble-Picker issue](https://user-images.githubusercontent.com/33920792/115514808-1336b780-a2b7-11eb-895f-3d90618174e2.PNG)

**Comment by anantcodes** [comment]
Issue resolved yet?

**Comment by KentBryan** [comment]
Yes, it's working now

**Comment by anantcodes** [comment]
Great

**Comment by joey-kb** [comment]
@KentBryan Could you explain how you fixed this? Im stuck on this issue..

**Comment by aman-reso** [comment]
When i am going to one activity to Bubble Activity and again doing same Process the app has crashed

**Comment by KentBryan** [comment]
@joeywittig my solution in crashing issue, is to revise some line of codes under "physics" directory

**physics** -> **Engine** -> **then search the function "clear"**

This is my solution, just replace the code inside that function to this.

```
borders.forEach { if(world.isLocked) world.destroyBody(it.itemBody) }
bodies.forEach { if(world.isLocked)world.destroyBody(it.physicalBody) }
borders.clear()
bodies.clear()
```

your function "clear" should be like this:

```
fun clear() {
    borders.forEach { if(world.isLocked) world.destroyBody(it.itemBody) }
    bodies.forEach { if(world.isLocked)world.destroyBody(it.physicalBody) }
    borders.clear()
    bodies.clear()
}
```
